# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d165004e8b2482e5e198b0937e6f441a6383d0d1af7829dbd1ed677cb8d8b23f3c2bc09bb8a5c53a7d3d0a87c696e4a83d3dad2ab2ca1080f1ae71a2643847c

test:
  secret_key_base: c43f4abfae64df03659934f667d30e51f12b6539a702455a61f779b9cde95bd61c84c9771c39acdc5d93cee30292920efe004177aa054235e5ee8e07803c00d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
